server:
  port: 9030   # server.port：当前 Config Server 服务端口
spring:
  application:
    name: nativeconfigserver  # spring.application.name：当前服务注册在 Eureka Server 上的名称
  profiles:
    active: native    #profiles.active：配置文件获取方式
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared   # cloud.config.server.native.search-locations：本地配置文件的存放路径




